In [55]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [56]:
df = pd.read_csv("data/Weather_dataset.csv")
df.time = pd.to_datetime(df.time)
df.head()

,time,temperature,relative_humidity,dew_point,precipitation (mm),rain (mm),snowfall (cm),pressure_msl (hPa),surface_pressure (hPa),cloud_cover (%),cloud_cover_low (%),cloud_cover_mid (%),cloud_cover_high (%),vapour_pressure_deficit (kPa),wind_speed_10m (km/h),wind_direction
0,2000-01-01 00:00:00,-0.1,97,-0.5,0.0,0.0,0.0,1024.2,1019.3,87,76,3,56,0.02,5.9,169
1,2000-01-01 01:00:00,-0.2,97,-0.7,0.0,0.0,0.0,1024.4,1019.5,89,79,1,58,0.02,5.8,173
2,2000-01-01 02:00:00,-0.1,96,-0.6,0.0,0.0,0.0,1024.5,1019.6,100,89,9,80,0.02,6.1,180
3,2000-01-01 03:00:00,-0.2,96,-0.7,0.0,0.0,0.0,1024.2,1019.3,100,92,34,92,0.02,6.8,183
4,2000-01-01 04:00:00,-0.2,96,-0.8,0.0,0.0,0.0,1024.0,1019.1,100,76,51,98,0.02,6.8,183